# [BANCO_ITM]

In [0]:
USE [master]
GO

In [0]:
/****** Object:  Database [BANCO_ITM]    Script Date: 21/10/2023 10:59:48 a. m. ******/
CREATE DATABASE [BANCO_ITM]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'BANCO_ITM', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\BANCO_ITM.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'BANCO_ITM_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\BANCO_ITM_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [BANCO_ITM] SET COMPATIBILITY_LEVEL = 160
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [BANCO_ITM].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [BANCO_ITM] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [BANCO_ITM] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [BANCO_ITM] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [BANCO_ITM] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [BANCO_ITM] SET ARITHABORT OFF 
GO
ALTER DATABASE [BANCO_ITM] SET AUTO_CLOSE ON 
GO
ALTER DATABASE [BANCO_ITM] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [BANCO_ITM] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [BANCO_ITM] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [BANCO_ITM] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [BANCO_ITM] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [BANCO_ITM] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [BANCO_ITM] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [BANCO_ITM] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [BANCO_ITM] SET  ENABLE_BROKER 
GO
ALTER DATABASE [BANCO_ITM] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [BANCO_ITM] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [BANCO_ITM] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [BANCO_ITM] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [BANCO_ITM] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [BANCO_ITM] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [BANCO_ITM] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [BANCO_ITM] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [BANCO_ITM] SET  MULTI_USER 
GO
ALTER DATABASE [BANCO_ITM] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [BANCO_ITM] SET DB_CHAINING OFF 
GO
ALTER DATABASE [BANCO_ITM] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [BANCO_ITM] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [BANCO_ITM] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [BANCO_ITM] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [BANCO_ITM] SET QUERY_STORE = ON
GO
ALTER DATABASE [BANCO_ITM] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO

# [dbo].[Usuarios]

In [0]:
USE [BANCO_ITM]
GO

In [0]:
/****** Object:  Table [dbo].[Usuarios]    Script Date: 21/10/2023 10:59:49 a. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Usuarios](
	[Id_Usuario] [int] NULL,
	[Nombre] [varchar](15) NULL,
	[Apellido] [varchar](30) NULL,
	[Valor_Vivienda] [int] NULL,
	[Tasa] [decimal](18, 2) NULL,
	[Plazo] [int] NULL,
	[PorcentajeCuotaInicial] [decimal](18, 2) NULL,
	[ValorCuotaInicial] [decimal](18, 2) NULL,
	[Credito] [decimal](18, 2) NULL,
	[ValorBeneficio] [decimal](18, 2) NULL,
	[CuotaSinBeneficio] [decimal](18, 2) NULL,
	[CuotaConBeneficio] [decimal](18, 2) NULL
) ON [PRIMARY]
GO

In [0]:
INSERT [dbo].[Usuarios] ([Id_Usuario], [Nombre], [Apellido], [Valor_Vivienda], [Tasa], [Plazo], [PorcentajeCuotaInicial], [ValorCuotaInicial], [Credito], [ValorBeneficio], [CuotaSinBeneficio], [CuotaConBeneficio]) VALUES (1037594919, N'Esteban ', N'Palacios Montoya', 150000000, CAST(1.15 AS Decimal(18, 2)), 240, CAST(0.00 AS Decimal(18, 2)), CAST(0.00 AS Decimal(18, 2)), CAST(150000000.00 AS Decimal(18, 2)), CAST(450000.00 AS Decimal(18, 2)), CAST(1843532.63 AS Decimal(18, 2)), CAST(1393532.63 AS Decimal(18, 2)))
GO

# [dbo].[sp_create]

In [0]:
/****** Object:  StoredProcedure [dbo].[sp_create]    Script Date: 21/10/2023 10:59:49 a. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
	CREATE PROCEDURE [dbo].[sp_create]
    @Id_Usuario INT,
    @Nombre VARCHAR(100),
    @Apellido VARCHAR(100),
    @Valor_Vivienda DECIMAL(18, 2),
    @Tasa DECIMAL(18, 2),
    @Plazo INT,
    @PorcentajeCuotaInicial DECIMAL(18, 2),
    @ValorCuotaInicial DECIMAL(18, 2),
    @Credito DECIMAL(18, 2),
    @ValorBeneficio DECIMAL(18, 2),
    @CuotaSinBeneficio DECIMAL(18, 2),
    @CuotaConBeneficio DECIMAL(18, 2)
AS
BEGIN
    -- Tu lógica para insertar los datos en la tabla Usuarios
    -- Asegúrate de incluir todos los campos que deseas guardar en la tabla.

    INSERT INTO Usuarios (Id_Usuario, Nombre, Apellido, Valor_Vivienda, Tasa, Plazo, PorcentajeCuotaInicial, ValorCuotaInicial, Credito, ValorBeneficio, CuotaSinBeneficio, CuotaConBeneficio)
    VALUES (@Id_Usuario, @Nombre, @Apellido, @Valor_Vivienda, @Tasa, @Plazo, @PorcentajeCuotaInicial, @ValorCuotaInicial, @Credito, @ValorBeneficio, @CuotaSinBeneficio, @CuotaConBeneficio);
END
GO

# [dbo].[sp_delete]

In [0]:
/****** Object:  StoredProcedure [dbo].[sp_delete]    Script Date: 21/10/2023 10:59:49 a. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
create procedure [dbo].[sp_delete]
@Id int
as begin
delete from usuarios where Id_Usuario=@Id
end

select *from Usuarios
GO

# [dbo].[sp_load]

In [0]:
/****** Object:  StoredProcedure [dbo].[sp_load]    Script Date: 21/10/2023 10:59:49 a. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[sp_load]
AS
BEGIN
    SELECT * FROM Usuarios;
END
GO

# [dbo].[sp_read]

In [0]:
/****** Object:  StoredProcedure [dbo].[sp_read]    Script Date: 21/10/2023 10:59:49 a. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[sp_read]
    @Id INT
AS
BEGIN
    SELECT
        Id_Usuario,
        Nombre,
        Apellido,
        Valor_Vivienda,
        Tasa,
        Plazo,
        PorcentajeCuotaInicial,
        ValorCuotaInicial,
        Credito,
        ValorBeneficio,
        -- Calcular la cuota sin beneficio
        (Valor_Vivienda * 0.0115 * POWER(1 + 0.0115, Plazo)) / (POWER(1 + 0.0115, Plazo) - 1) AS CuotaSinBeneficio,
        -- Calcular la cuota con beneficio
        ((Valor_Vivienda * 0.0115 * POWER(1 + 0.0115, Plazo)) / (POWER(1 + 0.0115, Plazo) - 1)) - ValorBeneficio AS CuotaConBeneficio
    FROM
        Usuarios
    WHERE
        Id_Usuario = @Id;
END
GO

# [dbo].[sp_update]

In [0]:
/****** Object:  StoredProcedure [dbo].[sp_update]    Script Date: 21/10/2023 10:59:49 a. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[sp_update]
    @Id INT,
    @Nombre VARCHAR(50),
    @Apellido VARCHAR(50),
    @Valor_Vivienda DECIMAL(18, 2),
    @Tasa DECIMAL(18, 2),
    @Plazo INT,
    @PorcentajeCuotaInicial DECIMAL(18, 2),
    @ValorCuotaInicial DECIMAL(18, 2),
    @Credito DECIMAL(18, 2),
    @ValorBeneficio DECIMAL(18, 2),
    @CuotaSinBeneficio DECIMAL(18, 2),
    @CuotaConBeneficio DECIMAL(18, 2)
AS
BEGIN
    UPDATE Usuarios
    SET
        Nombre = @Nombre,
        Apellido = @Apellido,
        Valor_Vivienda = @Valor_Vivienda,
        Tasa = @Tasa,
        Plazo = @Plazo,
        PorcentajeCuotaInicial = @PorcentajeCuotaInicial,
        ValorCuotaInicial = @ValorCuotaInicial,
        Credito = @Credito,
        ValorBeneficio = @ValorBeneficio,
        CuotaSinBeneficio = @CuotaSinBeneficio,
        CuotaConBeneficio = @CuotaConBeneficio
    WHERE Id_Usuario = @Id;
END
GO

# [BANCO_ITM]

In [0]:
USE [master]
GO

In [0]:
ALTER DATABASE [BANCO_ITM] SET  READ_WRITE 
GO